# Generated by Django 4.0.4 on 2022-08-10 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Id', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=150)),
                ('Description', models.TextField()),
                ('Ratings', models.FloatField()),
                ('Techstack', models.TextField()),
                ('Owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Clg_Org', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
                ('Branch_Dept', models.CharField(max_length=100)),
                ('Working_status', models.BooleanField(default=True)),
                ('Achivements', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Linkedin', models.URLField()),
                ('Projects', models.ManyToManyField(to='panel.projects')),
            ],
        ),
    ]
