# Generated by Django 4.0.4 on 2022-08-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
