# Generated by Django 4.0.4 on 2022-08-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Achivements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
