# Generated by Django 4.0.4 on 2022-08-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_profile_achivements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Domain',
            field=models.CharField(default='Developer', max_length=200),
        ),
    ]
