# Generated by Django 4.0.4 on 2022-08-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Cgpa',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
