# Generated by Django 4.0.4 on 2022-08-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_profile_cgpa_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Cgpa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Clg_Org',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
